name: Backend workflow

on: 
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install
    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to Droplet
      env:
        DROPLET_IP: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
        DROPLET_PASSWORD: ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD }}
      run: |
        sshpass -p "${DROPLET_PASSWORD}" ssh -o StrictHostKeyChecking=no root@${DROPLET_IP} << 'EOF'

          apt-get update
          apt-get install -y nodejs npm

          cd ~

          git clone https://github.com/Mohit0135/movieBooking-Application.git 

          git fetch origin
          git checkout main
          git pull origin main

          npm install --legacy-peer-deps
          npm run build

          npm run start
        EOF