name: Backend workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd backend
          npm ci
      
      - name: List backend files
        run: |
          cd backend
          ls -la  # List all files to ensure the folder isn't empty

      # Step to zip the backend directory
      - name: Zip the backend folder
        run: |
          cd backend
          zip -r ../backend.zip . 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Copy zipped file to EC2 using SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.GREEN_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: backend.zip
          target: /home/ubuntu/

      - name: SSH into EC2 and deploy the application
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.GREEN_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            unzip -o /home/ubuntu/backend.zip -d /home/ubuntu/backend/
            cd /home/ubuntu/backend/
            npm install --production
            pm2 restart all  # Assuming you are using PM2 to manage the node app

      - name: Health Check on Green Environment
        run: |
          curl -f http://${{ secrets.GREEN_EC2_IP }}/health || exit 1

      - name: Terminate Blue Environment
        run: |
          aws ec2 terminate-instances --instance-ids ${{ secrets.BLUE_EC2_ID }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Post-deployment verification
        run: echo "Deployment and Blue-Green strategy executed successfully."
